### ISSUE TITLE
Перегрев "Сервера"

### ISSUE THREAD

**Issue by ABAHrAPD** [Relvl/Rimworld-DigitalStorageUnit#1]
Добавь возможность главному блоку ДСУ греться и без охлаждения получать урон .

**Comment by Relvl** [comment]
Добавлено.
Включается в опциях, по умолчанию выключено.
После включения сервер начинает выделять много тепла.
При достижении 100 градусов начинает дымить и выводить алерт о перегреве.
180 градусов - отправляется письмо с критической опасностью (игру на паузу).
200 градусов - ДСУ, все хранимые предметы, и все строения начинают получать урон. Чем выше нагрев комнаты - тем выше урон.

ДСУ перестаёт работать в комнате, соединенной с улицей, либо если в потолке есть дыры.

Вероятно, требуется баланс температур, урона.

В планах:
+ Отбалансировать лимит хранения, повышая его от включения системы перегрева
+ Добавить строения хранилищ данных, которые так же будут повышать лимит и немного снижать тепловыделение. Потребуют архотек технологию.
+ Добавить технологию, которая со включенным перегревом снизит тепловыделение, а с выключенным - немного повысит лимит хранения.
